### ISSUE TITLE
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'

### ISSUE THREAD

**Issue by kachook** [wawawario2/long_term_memory#12]
text-generation-webui redesigned their chat function, and it now contains additional argument:  'end_of_turn'
Chat no longer works with LTM plugin loaded due to next error:
```
prompt = custom_generate_chat_prompt(text, generate_state['max_new_tokens'], name1, name2, context, generate_state['chat_prompt_size'], **kwargs)
TypeError: custom_generate_chat_prompt() got an unexpected keyword argument 'end_of_turn'
```

**Comment by bubbabug** [comment]
I am also having this issue. Followed all steps in readme, passed the initial check. As soon as I try to generate text I receive this error. If I disable the long_term_memory extension, my bot runs as expected.

**Comment by Belarrius1** [comment]
I use the version of text-generation-webui from 3 days go because of this

**Comment by wawawario2** [comment]
Thank you for reporting this. This should now be fixed in [this commit](https://github.com/wawawario2/long_term_memory/commit/30cd60fc37b642e27f7f7e64d133cac21fc0ccc1)

**Comment by kachook** [comment]
> Thank you for reporting this. This should now be fixed in [this commit](https://github.com/wawawario2/long_term_memory/commit/30cd60fc37b642e27f7f7e64d133cac21fc0ccc1). Try pulling and let me know if it works for you.

All fixed now. Thanks for a quick turn around!
